version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=hoctin_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_pass

  redis:
    image: redis:7-alpine

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-key
      - DATABASE_URL=postgres://postgres:postgres_pass@db:5432/hoctin_db
      - REDIS_URL=redis://redis:6379/1
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  celery:
    build: .
    command: celery -A core_project worker -l info
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgres://postgres:postgres_pass@db:5432/hoctin_db
      - REDIS_URL=redis://redis:6379/1
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  static_volume:
  media_volume:
