# Generated by Django 4.2.30 on 2026-05-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_testownership_lessonprogress_courseownership'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='duration',
            field=models.PositiveIntegerField(default=60, help_text='Thời gian làm bài (phút)'),
        ),
    ]
