# Generated by Django 5.2.14 on 2026-05-17 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_test_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRegulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề quy chế')),
                ('content', models.TextField(verbose_name='Nội dung quy chế')),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='is_official',
            field=models.BooleanField(default=False, verbose_name='Kỳ thi chính thức'),
        ),
        migrations.AddField(
            model_name='testownership',
            name='agreed_rules',
            field=models.BooleanField(default=False, verbose_name='Đồng ý nội quy'),
        ),
        migrations.AddField(
            model_name='testownership',
            name='registered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm đăng ký'),
        ),
        migrations.AddField(
            model_name='test',
            name='regulation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.testregulation', verbose_name='Quy chế phòng thi'),
        ),
    ]
