# Generated by Django 5.2.14 on 2026-05-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_course_creator_profile_can_create_courses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Công khai (Học sinh có thể xem)'),
        ),
    ]
