# Generated by Django 5.2.14 on 2026-05-17 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_question_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='ignore_spaces',
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_case_sensitive',
        ),
    ]
