# Generated by Django 5.2.14 on 2026-05-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_remove_question_ignore_spaces_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Công khai (Học sinh có thể xem)'),
        ),
    ]
