# Generated by Django 5.2.14 on 2026-05-18 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_alter_question_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tên gợi nhớ của lời dẫn')),
                ('content', models.TextField(verbose_name='Nội dung lời dẫn (Markdown + LaTeX)')),
            ],
        ),
        migrations.RemoveField(
            model_name='testquestion',
            name='test_part',
        ),
        migrations.AddField(
            model_name='testquestion',
            name='part_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Thuộc phần mấy (1, 2, 3...)'),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='lms.test'),
        ),
        migrations.CreateModel(
            name='TestPartInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.PositiveIntegerField(verbose_name='Phần số (1, 2, 3...)')),
                ('instruction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.sharedinstruction', verbose_name='Lời dẫn chung')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_instructions', to='lms.test')),
            ],
            options={
                'ordering': ['part_number'],
                'unique_together': {('test', 'part_number')},
            },
        ),
        migrations.DeleteModel(
            name='TestPart',
        ),
    ]
