# Generated by Django 4.2.30 on 2026-05-19 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0009_sharedinstruction_remove_testquestion_test_part_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquivalentQuestionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên nhóm câu hỏi tương đương')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='equivalent_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='lms.equivalentquestiongroup', verbose_name='Nhóm câu hỏi tương đương'),
        ),
    ]
