# Generated by Django 4.2.30 on 2026-05-19 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0010_equivalentquestiongroup_question_equivalent_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicTest',
            fields=[
                ('test_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lms.test')),
                ('max_questions', models.PositiveIntegerField(default=40, verbose_name='Số câu tối đa')),
                ('total_points', models.FloatField(default=10.0, verbose_name='Tổng điểm đề thi')),
                ('dynamic_group_rules', models.TextField(blank=True, null=True, verbose_name='Quy tắc chọn từ nhóm (ví dụ 7:3, 9:2)')),
                ('dynamic_question_ids', models.TextField(blank=True, null=True, verbose_name='Danh sách ID câu hỏi chọn trực tiếp')),
            ],
            options={
                'verbose_name': 'Đề thi động',
                'verbose_name_plural': 'Đề thi động',
            },
            bases=('lms.test',),
        ),
        migrations.AddField(
            model_name='attemptanswer',
            name='points',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='attemptanswer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.question'),
        ),
        migrations.AlterField(
            model_name='attemptanswer',
            name='test_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.testquestion'),
        ),
    ]
