# Generated by Django 4.2.30 on 2026-05-19 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0011_dynamictest_attemptanswer_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('THEORY', 'Bài học lý thuyết'), ('EXERCISE', 'Bài tập thực hành'), ('TEST', 'Bài kiểm tra / Đề thi')], default='THEORY', max_length=20, verbose_name='Loại bài học'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.test', verbose_name='Đề thi liên kết'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(blank=True, verbose_name='Nội dung lý thuyết (Markdown)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order_index',
            field=models.PositiveIntegerField(default=1, verbose_name='Thứ tự bài học'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='Link video bài học'),
        ),
    ]
