# Generated by Django 4.2.30 on 2026-05-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0012_lesson_lesson_type_lesson_test_alter_lesson_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_type',
            field=models.CharField(choices=[('STANDALONE', 'Đề thi riêng lẻ'), ('LESSON_ONLY', 'Đề thi gắn vào bài học')], default='STANDALONE', max_length=20, verbose_name='Loại đề thi'),
        ),
    ]
