# Generated by Django 5.2.14 on 2026-05-20 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0013_test_test_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='lms.course'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='course_bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='lms.coursebundle'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='lms.test'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='test_bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='lms.testbundle'),
        ),
    ]
