# Generated by Django 5.2.14 on 2026-05-20 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0014_wallettransaction_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Tên ngân hàng')),
                ('bank_code', models.CharField(max_length=20, verbose_name='Mã ngân hàng (ví dụ: VCB, MB, TCB)')),
                ('account_number', models.CharField(max_length=50, verbose_name='Số tài khoản')),
                ('account_holder', models.CharField(max_length=100, verbose_name='Chủ tài khoản')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tài khoản ngân hàng',
                'verbose_name_plural': 'Các tài khoản ngân hàng',
            },
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='lms.bankaccount', verbose_name='Ngân hàng thụ hưởng'),
        ),
    ]
