# Generated by Django 5.2.14 on 2026-05-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0015_bankaccount_wallettransaction_bank_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration_days',
            field=models.PositiveIntegerField(default=30, help_text='Số ngày được học kể từ lúc mua/duyệt. Nhập 0 hoặc để trống nếu muốn học trọn đời.', verbose_name='Thời hạn học (ngày)'),
        ),
        migrations.AddField(
            model_name='courseownership',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Thời điểm hết hạn học khóa học này. Để trống nghĩa là học trọn đời.', null=True, verbose_name='Ngày hết hạn'),
        ),
    ]
