# Generated by Django 5.2.14 on 2026-05-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0016_course_duration_days_courseownership_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, default=30, help_text='Số ngày được học kể từ lúc mua/duyệt. Nhập 0 hoặc để trống nếu muốn học trọn đời.', null=True, verbose_name='Thời hạn học (ngày)'),
        ),
    ]
