# Generated by Django 4.2.30 on 2026-05-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0017_alter_course_duration_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='position',
            field=models.IntegerField(default=1),
        ),
    ]
