# Generated by Django 5.2.14 on 2026-05-23 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0018_alter_choice_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Mô tả ngắn về đề thi'),
        ),
    ]
