# Generated by Django 5.2.14 on 2026-05-23 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0019_test_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='left_page_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Số lần rời khỏi trang'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='left_page_time',
            field=models.PositiveIntegerField(default=0, verbose_name='Tổng thời gian rời khỏi trang (giây)'),
        ),
    ]
