# Generated by Django 5.2.14 on 2026-05-25 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0020_attempt_left_page_count_attempt_left_page_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='shuffle_parts',
            field=models.BooleanField(default=False, help_text='Nếu đề thi có nhiều phần, cho phép đảo ngẫu nhiên các phần đó.', verbose_name='Đảo ngẫu nhiên các phần'),
        ),
    ]
