# Generated by Django 5.2.14 on 2026-05-31 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0021_test_shuffle_parts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('THEORY', 'Bài học lý thuyết'), ('EXERCISE', 'Bài tập thực hành'), ('TEST', 'Bài kiểm tra / Đề thi'), ('MULTI_EXERCISE', 'Đa bài tập lập trình')], default='THEORY', max_length=20, verbose_name='Loại bài học'),
        ),
        migrations.CreateModel(
            name='MultiExerciseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(verbose_name='Đường dẫn bài tập')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tiến độ đa bài tập',
                'verbose_name_plural': 'Tiến độ đa bài tập',
                'unique_together': {('user', 'lesson', 'link')},
            },
        ),
    ]
