# Generated by Django 4.2.30 on 2026-06-06 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0022_alter_lesson_lesson_type_multiexerciseprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên lớp học')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả lớp học')),
                ('invite_code', models.CharField(default=uuid.uuid4, max_length=50, unique=True, verbose_name='Mã mời')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classroom_course', to='lms.course', verbose_name='Khóa học nội bộ')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_classrooms', to=settings.AUTH_USER_MODEL, verbose_name='Giáo viên')),
            ],
        ),
        migrations.CreateModel(
            name='ClassroomItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lms.classroom')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_items', to='lms.lesson')),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassroomMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ duyệt'), ('APPROVED', 'Đã phê duyệt')], default='PENDING', max_length=15)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='lms.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('classroom', 'student')},
            },
        ),
    ]
